[package]
name = "tuido"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
serde = "1.0.139"
serde_derive = "1.0.139"
serde_json = "1.0.82"
tui = "0.18.0"
unicode-width = "0.1.9"
