[env]
BIN_NAME="tuido"
COMPILER_FLAGS="--release"

[build]
cmd = """
cargo build &&
cp -r ./target/debug/$BIN_NAME ./bin/$BIN_NAME
"""

[[custom]]
name = "clean"
cmd = "cargo clean"
run = false

[[custom]]
name = "setup"
cmd = """
mkdir -p bin &&
rustup install stable &&
rustup default stable
"""
run = false

[[custom]]
name = "release"
cmd = """
cargo build $COMPILER_FLAGS &&
cp -r ./target/release/$BIN_NAME ./bin/$BIN_NAME
"""
run = false

[[pre]]
name = "fmt"
cmd = "cargo fmt"
